eAuction/eAuction/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eAuction.Models
{
    public class Item
    {
        public string Name { get; set; }
        public int Estimate { get; set; }
        public int Current { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public DateTime Sale_End { get; set; }
    }
}

eAuction/eAuction/Pages/Add.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eAuction.Helpers;
using eAuction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eAuction.Pages
{
    public class AddModel : PageModel
    {
        [BindProperty]
        public Item Item { get; set; }
        public Helper Helper { get; set; }

        public AddModel()
        {
            Helper = new Helper();
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }

            Helper.AddNew(Item);

            return RedirectToPage("Add");
        }
    }
}

eAuction/eAuction/Pages/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using eAuction.Helpers;
using eAuction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eAuction.Pages
{
    public class EditModel : PageModel
    {

        [BindProperty]
        public Item Item { get; set; }
        public Helper Helper { get; set; }
        [BindProperty]
        public int Id { get; set; }

        public EditModel()
        {
            Helper = new Helper();
        }

        public void OnGet(int id)
        {
            Id = id;
            Item = Helper.FetchItem(id);
        }
        public IActionResult OnPost()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }

            Helper.EditItem(Item, Id);

            return Redirect("Single?id=" + Id);
        }
    }
}

eAuction/eAuction/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eAuction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ServiceStack.Redis;
using Newtonsoft.Json;
using System.Text;
using eAuction.Helpers;

namespace eAuction.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        Helper Helper { get; set; }
        public IList<(Item Item, int Id)> items { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;

            Helper = new Helper();
            Helper.InitialStartUp();
        }

        public void OnGet()
        {
            items = Helper.FetchAll();
        }

        public void OnGetCategory(string category)
        {
            items = Helper.FetchCategory(category);
        }
    }
}

eAuction/eAuction/Pages/Single.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using eAuction.Helpers;
using eAuction.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace eAuction.Pages
{
    public class SingleModel : PageModel
    {
        Helper Helper { get; set; }
        [BindProperty]
        public Item Item { get; set; }
        [BindProperty]
        public int Id { get; set; }
        [BindProperty]
        public int NewBid { get; set; }
        public IList<(Item Item, int Id)> items { get; set; }

        public SingleModel()
        {
            Helper = new Helper();
        }

        public void OnGet(int id)
        {
            Id = id;
            Item = Helper.FetchItem(id);

            items = Helper.FetchAll();

            var index = -1;
            for (int i = 0; i < items.Count; i++)
                if (items[i].Id == Id)
                {
                    index = i;
                    break;
                }

            items.RemoveAt(index);
        }

        public IActionResult OnPostBid()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }

            if (NewBid > Item.Current)
                Helper.PlaceBid(Id, NewBid);

            return Redirect("Single?id=" + Id);
        }

        public IActionResult OnPostDelete()
        {
            if (!this.ModelState.IsValid)
            {
                return this.Page();
            }

            Helper.DeleteItem(Id);

            return RedirectToPage("Index");
        }
    }
}

eAuction/eAuction/Pages/Add.cshtml
@page
@model eAuction.Pages.AddModel
@{
    ViewData["Title"] = "Sell";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
</head>

<body>
    <header id="header">
        <div class="header-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 clearfix">
                        <div class="logo pull-left">
                            <a asp-page="Index"><img src="images/home/logo.png" alt="" /></a>
                        </div>
                    </div>
                    <div class="col-md-8 clearfix">
                        <div class="shop-menu clearfix pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href=""><i class="fa fa-user"></i> Account</a></li>
                                <li><a href=""><i class="fa fa-lock"></i> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="header-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a asp-page="Index" class="active">Home</a></li>
                                <li class="dropdown">
                                    <a asp-page="Index">Categories<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="shop.html">Watches & Jewellery</a></li>
                                        <li><a href="product-details.html">Fine Art</a></li>
                                        <li><a href="checkout.html">Furniture</a></li>
                                        <li><a href="cart.html">Vintage Fashion</a></li>
                                    </ul>
                                </li>
                                <li><a asp-page="Add">Sell</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section id="form">
        <div class="container">
            <div class="row">
                <div class="add-item-form">
                    <div class="col-sm-4 col-sm-offset-1">
                        <h2>Add an item to sell</h2>
                        <form method="post">
                            <p>Name:</p>
                            <input asp-for="@Model.Item.Name" type="text" placeholder="Name" required="" />
                            <p>Category:</p>
                            <select asp-for="@Model.Item.Category" required="">
                                <option value="" disabled selected>Select category</option>
                                <option value="Watches & Jewellery">Watches & Jewellery</option>
                                <option value="Fine Art">Fine Art</option>
                                <option value="Furniture">Furniture</option>
                                <option value="Vintage Fashion">Vintage Fashion</option>
                            </select>
                            <p>Your estimate:</p>
                            <input asp-for="@Model.Item.Estimate" type="number" placeholder="Your estimate ($)" required="" />
                            <p>Opening price:</p>
                            <input asp-for="@Model.Item.Current" type="number" placeholder="Opening price ($)" required="" />
                            <p>Description:</p>
                            <textarea asp-for="@Model.Item.Description" placeholder="Description" required=""> </textarea>
                            <p>Sale end</p>
                            <input asp-for="@Model.Item.Sale_End" type="datetime-local" required="" />
                            <button type="submit" class="btn btn-default">Sell</button>
                        </form>
                    </div>
                </div>        
            </div>
        </div>
    </section>


    <footer id="footer">

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2021 eAuction. All rights reserved.</p>
                    <p class="pull-right">Designed by Miloš Veljanovski</p>
                </div>
            </div>
        </div>

    </footer>

    <script src="js/jquery.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

eAuction/eAuction/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "eAuction";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
</head>

<body>
    <header id="header">    

        <div class="header-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 clearfix">
                        <div class="logo pull-left">
                            <a asp-page="Index"><img src="images/home/logo.png" alt="" /></a>
                        </div>
                    </div>
                    <div class="col-md-8 clearfix">
                        <div class="shop-menu clearfix pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href=""><i class="fa fa-user"></i> Account</a></li>
                                <li><a href=""><i class="fa fa-lock"></i> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="header-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">              
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a asp-page="Index" class="active">Home</a></li>
                                <li class="dropdown">
                                    <a asp-page="Index">Categories<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a asp-route-category="Watches & Jewellery" asp-page-handler="Category">Watches & Jewellery</a></li>
                                        <li><a asp-route-category="Fine Art" asp-page-handler="Category">Fine Art</a></li>
                                        <li><a asp-route-category="Furniture" asp-page-handler="Category">Furniture</a></li>
                                        <li><a asp-route-category="Vintage Fashion" asp-page-handler="Category">Vintage Fashion</a></li>
                                    </ul>
                                </li>
                                <li><a asp-page="Add">Sell</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>Category</h2>
                        <div class="panel-group category-products" id="accordian">
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><a asp-route-category="Watches & Jewellery" asp-page-handler="Category">Watches & Jewellery</a></h4>                                 
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><a asp-route-category="Fine Art" asp-page-handler="Category">Fine Art</a></h4>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><a asp-route-category="Furniture" asp-page-handler="Category">Furniture</a></h4>
                                </div>
                            </div>
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title"><a asp-route-category="Vintage Fashion" asp-page-handler="Category">Vintage Fashion</a></h4>
                                </div>
                            </div>
                        </div>                     

                    </div>
                </div>

                <div class="col-sm-9 padding-right">
                    <div class="features_items">
                        <h2 class="title text-center">Featured Items</h2>
                    @foreach(var i in Model.items)
                    {
                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">
                                    <div class="productinfo text-center">
                                        <a asp-page="Single" asp-route-id="@i.Id">
                                            <img src="images/@(i.Item.Name).jpg" alt="" />
                                        </a>
                                        <h2>$@i.Item.Current</h2>
                                        <p>@i.Item.Name</p>
                                        <a asp-page="Single" asp-route-id="@i.Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Bid</a>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
                    }
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer id="footer">
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2021 eAuction. All rights reserved.</p>
                    <p class="pull-right">Designed by Miloš Veljanovski</p>
                </div>
            </div>
        </div>
    </footer>



    <script src="js/jquery.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>

eAuction/eAuction/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"] - eAuction</title>
</head>
<body>
    @RenderBody()

    @RenderSection("Scripts", required: false)
</body>
</html>

eAuction/eAuction/Pages/Single.cshtml
@page
@model eAuction.Pages.SingleModel
@{
    ViewData["Title"] = "Single";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
</head>

<body>
    <header id="header">
        <div class="header-middle">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 clearfix">
                        <div class="logo pull-left">
                            <a asp-page="Index"><img src="images/home/logo.png" alt="" /></a>
                        </div>
                    </div>
                    <div class="col-md-8 clearfix">
                        <div class="shop-menu clearfix pull-right">
                            <ul class="nav navbar-nav">
                                <li><a href=""><i class="fa fa-user"></i> Account</a></li>
                                <li><a href=""><i class="fa fa-lock"></i> Login</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="header-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a asp-page="Index" class="active">Home</a></li>
                                <li class="dropdown">
                                    <a asp-page="Index">Categories<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a asp-page="Index" asp-route-category="Watches & Jewellery" asp-page-handler="Category">Watches & Jewellery</a></li>
                                        <li><a asp-page="Index" asp-route-category="Fine Art" asp-page-handler="Category">Fine Art</a></li>
                                        <li><a asp-page="Index" asp-route-category="Furniture" asp-page-handler="Category">Furniture</a></li>
                                        <li><a asp-page="Index" asp-route-category="Vintage Fashion" asp-page-handler="Category">Vintage Fashion</a></li>
                                    </ul>
                                </li>
                                <li><a asp-page="Add">Sell</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 padding-right">
                    <div class="product-details">
                        <div class="col-sm-4">
                            <div class="view-product">
                                <img src="images/@(Model.Item.Name).jpg" alt="" />
                            </div>

                        </div>
                        <div class="col-sm-8">
                            <div class="product-information">
                                <form method="post">
                                    <h2>@Model.Item.Name</h2>
                                    <p>Auctioneer's estimate: $@Model.Item.Estimate</p>
                                    <span>
                                        <span>Current bid: $@Model.Item.Current</span>
                                        <label>Your bid:</label>
                                        <input type="number" min="0" value="@(Math.Ceiling(Model.Item.Current+0.05*Model.Item.Current))" asp-for="@Model.NewBid" />$
                                        <input type="hidden" value="@Model.Item.Current" asp-for="@Model.Item.Current" />
                                        <button type="submit" asp-page-handler="Bid" class="btn btn-fefault cart">
                                            <i class="fa fa-shopping-cart"></i>
                                            Place bid
                                        </button>
                                        <input type="hidden" value="@Model.Id" asp-for="@Model.Id" />
                                    </span>
                                    <p><b>Description:</b> @Model.Item.Description</p>
                                    <p><b>Category:</b> @Model.Item.Category</p>
                                    <p><b>Sale date:</b> @Model.Item.Sale_End</p>
                                </form>
                                <form method="post">
                                    <a asp-page="Edit" asp-route-id="@Model.Id" class="btn btn-default add-to-cart"><i class="fa fa-pencil"></i>Edit</a>
                                    <button type="submit" asp-page-handler="Delete" class="btn btn-default add-to-cart"><i class="fa fa-trash-o"></i>Delete</button>
                                    <input type="hidden" value="@Model.Id" asp-for="@Model.Id" />
                                </form>
                            </div>
                        </div>
                    </div>

                    <div class="recommended_items">
                        <h2 class="title text-center">recommended items</h2>

                        <div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                <div class="item active">
                                    @for (int k = 0; k < 3; k++)
                                    {
                                        <div class="col-sm-4">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="text-center">
                                                        <a asp-page="Single" asp-route-id="@Model.items[k].Id">
                                                            <img src="images/@(Model.items[k].Item.Name)_R.jpg" alt="" />
                                                        </a>
                                                        <h2>$@Model.items[k].Item.Current</h2>
                                                        <p>@Model.items[k].Item.Name</p>
                                                        <a asp-page="Single" asp-route-id="@Model.items[k].Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Bid</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }

                                </div>
                                <div class="item">
                                    @for (int j = Model.items.Count - 1; j > Model.items.Count - 4; j--)
                                    {
                                        <div class="col-sm-4">
                                            <div class="product-image-wrapper">
                                                <div class="single-products">
                                                    <div class="text-center">
                                                        <a asp-page="Single" asp-route-id="@Model.items[j].Id">
                                                            <img src="images/@(Model.items[j].Item.Name)_R.jpg" alt="" />
                                                        </a>
                                                        <h2>$@Model.items[j].Item.Current</h2>
                                                        <p>@Model.items[j].Item.Name</p>
                                                        <a asp-page="Single" asp-route-id="@Model.items[j].Id" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Bid</a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </div>
                            </div>
                            <a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                            <a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <footer id="footer">

        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2021 eAuction. All rights reserved.</p>
                    <p class="pull-right">Designed by Miloš Veljanovski</p>
                </div>
            </div>
        </div>

    </footer>

    <script src="js/jquery.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>